version: 2

project_name: nexo

before:
  hooks:
    - go mod tidy

builds:
  - id: nexo
    main: ./cmd/nexo
    binary: nexo
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/abdul-hamid-achik/nexo/internal/version.Version={{.Version}}

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: abdul-hamid-achik
    name: nexo
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"

homebrew_casks:
  - name: nexo-cli
    ids:
      - default
    binaries:
      - nexo
    repository:
      owner: abdul-hamid-achik
      name: homebrew-nexo-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: https://github.com/abdul-hamid-achik/nexo
    description: A file-system based Go framework for APIs and websites
    commit_msg_template: "Brew cask update for {{ .ProjectName }} version {{ .Tag }}"
    directory: Casks
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nexo"]
          end
