# Taskfile for Nexo
# https://taskfile.dev
#
# Usage:
#   task build     # Build the CLI
#   task test      # Run tests
#   task install   # Install globally
#   task --list    # Show all tasks

version: '3'

vars:
  BINARY: nexo
  VERSION:
    sh: git describe --tags --always --dirty 2>/dev/null || echo "dev"

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  build:
    desc: Build the CLI binary
    cmds:
      - echo "Building {{.BINARY}}..."
      - go build -ldflags "-X github.com/abdul-hamid-achik/nexo/internal/version.Version={{.VERSION}}" -o bin/{{.BINARY}} ./cmd/nexo
      - echo "Done bin/{{.BINARY}}"
    sources:
      - "**/*.go"

  install:
    desc: Install the CLI globally
    cmds:
      - echo "Installing {{.BINARY}}..."
      - go install -ldflags "-X github.com/abdul-hamid-achik/nexo/internal/version.Version={{.VERSION}}" ./cmd/nexo
      - echo "Done {{.BINARY}} installed"

  test:
    desc: Run all tests
    cmds:
      - echo "Running tests..."
      - go test -v ./...

  test-short:
    desc: Run tests (short output)
    cmds:
      - go test ./...

  test-cover:
    desc: Run tests with coverage report
    cmds:
      - echo "Running tests with coverage..."
      - go test -v -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html
      - echo "Coverage report coverage.html"

  test-race:
    desc: Run tests with race detector
    cmds:
      - go test -race ./...

  lint:
    desc: Run linter (requires golangci-lint)
    cmds:
      - echo "Running linter..."
      - golangci-lint run

  fmt:
    desc: Format code
    cmds:
      - echo "Formatting code..."
      - go fmt ./...

  vet:
    desc: Vet code for issues
    cmds:
      - echo "Vetting code..."
      - go vet ./...

  check:
    desc: Run all checks (fmt, vet, test)
    cmds:
      - task fmt
      - task vet
      - task test-short

  dev:
    desc: Run development server
    cmds:
      - go run ./cmd/nexo dev

  clean:
    desc: Remove build artifacts
    cmds:
      - echo "Cleaning..."
      - rm -rf bin/
      - rm -rf dist/
      - rm -f coverage.out coverage.html
      - echo "Done"

  build-all:
    desc: Build for all platforms
    cmds:
      - task clean
      - echo "Building for all platforms..."
      - GOOS=darwin GOARCH=amd64 go build -ldflags "-X github.com/abdul-hamid-achik/nexo/internal/version.Version={{.VERSION}}" -o dist/{{.BINARY}}-darwin-amd64 ./cmd/nexo
      - GOOS=darwin GOARCH=arm64 go build -ldflags "-X github.com/abdul-hamid-achik/nexo/internal/version.Version={{.VERSION}}" -o dist/{{.BINARY}}-darwin-arm64 ./cmd/nexo
      - GOOS=linux GOARCH=amd64 go build -ldflags "-X github.com/abdul-hamid-achik/nexo/internal/version.Version={{.VERSION}}" -o dist/{{.BINARY}}-linux-amd64 ./cmd/nexo
      - GOOS=linux GOARCH=arm64 go build -ldflags "-X github.com/abdul-hamid-achik/nexo/internal/version.Version={{.VERSION}}" -o dist/{{.BINARY}}-linux-arm64 ./cmd/nexo
      - GOOS=windows GOARCH=amd64 go build -ldflags "-X github.com/abdul-hamid-achik/nexo/internal/version.Version={{.VERSION}}" -o dist/{{.BINARY}}-windows-amd64.exe ./cmd/nexo
      - echo "Done binaries in dist/"

  release-snapshot:
    desc: Create a snapshot release with goreleaser
    cmds:
      - goreleaser release --snapshot --clean

  routes:
    desc: List all routes in the app directory
    cmds:
      - go run ./cmd/nexo routes

  new:
    desc: Create a new Nexo project
    cmds:
      - go run ./cmd/nexo new {{.CLI_ARGS}}
